export const FETCH_TOP_ARTICLES = 'FETCH_TOP_ARTICLES';
export const FETCH_TOP_ARTICLES_SUCCESS = 'FETCH_TOP_ARTICLES_SUCCESS';
export const FETCH_TOP_ARTICLES_ERROR = 'FETCH_TOP_ARTICLES_ERROR';

export const FETCH_CATEGORY_ARTICLES = 'FETCH_CATEGORY_ARTICLES';
export const FETCH_CATEGORY_ARTICLES_SUCCESS = 'FETCH_CATEGORY_ARTICLES_SUCCESS';
export const FETCH_CATEGORY_ARTICLES_ERROR = 'FETCH_CATEGORY_ARTICLES_ERROR';

export const FETCH_SEARCH_TOP_ARTICLES = 'FETCH_SEARCH_TOP_ARTICLES';
export const FETCH_SEARCH_TOP_ARTICLES_SUCCESS = 'FETCH_SEARCH_TOP_ARTICLES_SUCCESS';
export const FETCH_SEARCH_TOP_ARTICLES_ERROR = 'FETCH_SEARCH_TOP_ARTICLES_ERROR`';
