export const TEST = 'TEST';

export const TEST_FETCH_REQUESTED = 'TEST_FETCH_REQUESTED';
export const TEST_FETCH_SUCCEEDED = 'TEST_FETCH_SUCCEEDED';
export const TEST_FETCH_FAILED = 'TEST_FETCH_FAILED';

